CREATE TABLE "ES_INDEXES" (
	"IP_ADDRESS"	TEXT NOT NULL,
	"PORT"	INTEGER NOT NULL,
	"INDEX"	TEXT NOT NULL,
	"UUID"	TEXT NOT NULL,
	"DOCS_COUNT"	INTEGER,
	"DOCS_DELETED"	INTEGER,
	"STORE_SIZE"	INTEGER,
	"STORE_SIZE_BYTES"	INTEGER,
	"INSERTED_DATE"	INTEGER DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_DATE"	INTEGER DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("UUID","IP_ADDRESS","PORT")
);