CREATE TABLE "ES_SAMPLES" (
	"DOCUMENT_ID"	TEXT,
	"UUID"	TEXT NOT NULL,
	"IP_ADDRESS"	TEXT NOT NULL,
	"PORT"	INTEGER NOT NULL,
	"INDEX"	TEXT,
	"SAMPLE"	TEXT NOT NULL,
	"INSERTED_DATE"	INTEGER DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_DATE"	INTEGER DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("UUID", "IP_ADDRESS","PORT", "INDEX", "DOCUMENT_ID"),
	FOREIGN KEY("UUID","IP_ADDRESS","PORT") REFERENCES "ES_INDEXES"("UUID","IP_ADDRESS","PORT")
);